name: infresnel
channels:
  - conda-forge
dependencies:
  - colorcet
  - ipympl
  - ipywidgets
  - joblib
  - jupyterlab
  - matplotlib
  - numba
  - pip
  - pygmt
  - rioxarray
  - scipy
  - tqdm
  - pip:
    - --editable .
